### ISSUE TITLE
Building with a headless appmanifest on Windows doesn't work, bundling does

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2129]
The editor hides the console window even with a headless build

This also makes it so if you attempt to build a headless build bundling after will not work and you must restart Defold editor to make bundling work

Sample headless.appmanifest

```
# App manifest generated Fri Aug 17 2018 00:53:01 GMT-0700 (Pacific Daylight Time)
# Settings: Physics,Record,Profiler,Facebook,Sound,Graphics,Input,Debug
platforms:
    x86_64-osx:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]

    x86_64-linux:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]

    js-web:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]

    x86-win32:
        context:
            excludeLibs: ["libBulletDynamics","libBulletCollision","libLinearMath","libBox2D","libphysics","librecord","libvpx","libprofilerext","libsound","libtremolo","libgraphics","libhid","libengine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["libengine.lib","libphysics_null.lib","librecord_null.lib","libsound_null.lib","libgraphics_null.lib","libhid_null.lib"]

    x86_64-win32:
        context:
            excludeLibs: ["libBulletDynamics","libBulletCollision","libLinearMath","libBox2D","libphysics","librecord","libvpx","libprofilerext","libsound","libtremolo","libgraphics","libhid","libengine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["libengine.lib","libphysics_null.lib","librecord_null.lib","libsound_null.lib","libgraphics_null.lib","libhid_null.lib"]

    armv7-android:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]

    armv7-ios:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]

    arm64-ios:
        context:
            excludeLibs: ["BulletDynamics","BulletCollision","LinearMath","Box2D","physics","record","vpx","profilerext","sound","tremolo","graphics","hid","engine"]
            excludeSymbols: ["ProfilerExt","FacebookExt","DefaultSoundDevice","AudioDecoderWav","AudioDecoderStbVorbis","AudioDecoderTremolo"]
            libs: ["engine","physics_null","record_null","sound_null","graphics_null","hid_null"]


```
