### ISSUE TITLE
Excluding Facebook SDK using App Manifest cause compiler error when bundling for HTML 5

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#2529]
Tested with new empty project on MacOS. This happens only for "html 5" bundle.
Bundle fine with Facebook SDK.

Example app manifest(build with latest manifest generator): [generated.appmanifest.zip](https://github.com/defold/editor2-issues/files/3009571/generated.appmanifest.zip)

Defold version:
![Screen Shot 2019-03-26 at 20 59 30](https://user-images.githubusercontent.com/1324635/55021585-12fd5c80-500a-11e9-9577-e72e78b05da0.png)

Error:

![Screen Shot 2019-03-26 at 21 00 49](https://user-images.githubusercontent.com/1324635/55021678-42ac6480-500a-11e9-895d-f82adaeb35a2.png)

**Comment by mathiaswking** [comment]
This is issue DEF-3874:

I haven't tried it, but you could try not excluding the "facebook_iap" library, which is the one implementing the dmFBIAPList function:

```yaml
    js-web:
        context:
            excludeLibs: ["facebookext"]
            excludeJsLibs: ["facebook"]
            excludeSymbols: ["FacebookExt"]
            libs: []
            linkFlags: []

    wasm-web:
        context:
            excludeLibs: ["facebookext"]
            excludeJsLibs: ["facebook"]
            excludeSymbols: ["FacebookExt"]
            libs: []
            linkFlags: []
```
